# Data Visualisation
This Jupyter Notebook is meant to help us visualise and analyse the data from traindata.txt and trainlabels.txt. Ensure you have downloaded the text files from Moodle and that you include their directories into this notebook otherwise your code won't run. GitHub doesn't allow for very large file uploads and frankly trying to find a way around this is an unnecessary fight since we all can get copies of the same data on the click of a button. Furthermore, ensure you use the prescribed libraries as seen in the instruction brief. The first part I wrote contains simple visualisation code you can mess with to get you started. Happy coding :)

#### Imports

In [1]:
# pip install pandas==2.2.2

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

C:\Users\User\AppData\Local\Temp\ipykernel_54756\3267135575.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

#### Reading the data
Ensure you change the traindata.txt to reference a file on your device or wherever you chose to put it.

In [2]:
data = pd.read_csv('C:\\Users\\User\\Documents\\CS Year 3\\ML\\Assignment 2\\traindata.txt', header=None)

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

data.head(10)
# data.tail(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,33.167786,9.462100,50.246693,24.813057,29.595383,6.788610,10.017276,36.381538,65.653381,46.273445,44.087254,16.133245,31.117434,21.409285,54.702248,70.609848,45.672382,31.430090,34.358063,55.136074,52.269527,42.455395,55.080475,21.243286,6.753647,25.871201,53.891422,47.219788,56.719131,16.771717,46.825405,19.309006,25.698381,39.105648,7.983992,12.893216,67.092201,54.356434,34.184410,174.163208,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,247.386414,255.000000,255.000000,255.000000,255.000000,255.000000,151.252426,78.103645,35.468491,17.590273,65.632111,6.858457,8.564450,1.416216,69.159416,226.985855,54.106178,60.206211,30.465374,446.326599,65.150154,187.761261,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,-31.0,1454.685913,78.503777,60.349628,-171.0,713.418884,19.567923,66.388382,164.258423,15.367357,-179.0,430.336975,34.296913,22.134666,46.519905,32.130516,70.650017,83.558502,155.336136,255.000000,255.000000,255.000000,255.000000,255.000000,247.956512,250.468674,255.000000,255.000000,255.000000,255.000000,255.000000,247.183289,255.000000,255.000000,255.000000,126.542534,80.508438,45.694820,60.982803,2.574840,32.149372,7.617475,37.710590,29.843725,10.479345,39.925377,585.572449,63.323456,37.983578,59.047035,167.502380,255.000000,245.193405,191.395767,98.929413,100.156303,139.002228,127.084572,62.722248,92.380547,74.891663,99.167809,112.526184,102.935287,191.892471,245.303818,255.000000,149.674911,77.874466,2.136170,12.489136,11.637994,9.335680,21.840355,14.159405,62.824093,64.901291,50.423645,56.419449,50.300976,8.967319,78.253349,147.158920,255.000000,2550.000000,103.430702,53.649139,37.072945,26.140141,58.810478,13.029821,23.490004,74.221489,40.422390,25.005428,35.293800,153.922607,255.000000,255.000000,130.218826,76.770744,354.686066,61.343117,35.204582,14.828337,55.840309,26.231688,2.458547,24.726635,26.589281,31.490585,4.638988,54.817616,46.029129,191.393280,255.000000,255.000000,121.992592,40.858238,25.329493,72.426727,-178.0,26.176260,1.349862,25.651743,74.341560,11.786539,8.677136,52.786274,162.698654,255.000000,255.000000,172.253128,51.868183,38.521328,66.128220,47.667866,15.760224,73.477242,36.068832,0.140351,44.769981,43.845051,8.915479,47.436596,74.319885,21.604380,200.881104,2550.000000,255.000000,140.797516,34.404446,30.745207,25.831518,41.295486,45.431469,39.608017,14.739442,58.756016,78.708588,13.701618,140.071762,255.000000,255.000000,160.058990,62.996590,33.269966,50.085896,2.891373,54.905399,59.587563,59.263096,0.447568,41.392433,2.312485,19.323322,41.908867,59.789093,52.862022,186.752136,255.000000,255.000000,166.349487,69.604782,74.690826,57.756512,28.260298,33.493706,62.362885,28.466703,40.813755,39.265430,27.826820,163.617767,240.814301,255.000000,133.242249,44.388790,52.238323,713.047546,33.823494,6.666055,69.687187,8.775831,8.756810,14.676421,30.200274,72.294434,72.511414,68.186981,51.487041,149.059341,255.000000,255.000000,101.798172,1.193525,72.751625,29.779882,69.393211,55.532475,45.638069,27.397474,12.169411,14.803481,4.074387,106.758522,255.000000,255.000000,182.367722,25.437033,69.005142,61.676159,49.411259,43.174969,11.471530,56.420616,3.621758,2.893558,46.950485,32.224945,69.106613,30.997135,46.278709,133.537643,255.000000,254.827316,124.128593,74.845757,67.936302,37.679974,46.929722,22.107811,39.168800,50.589260,51.772835,2.609788,42.473938,142.313004,240.600845,255.000000,135.707077,31.025183,35.747452,29.904764,31.175770,28.456181,25.444906,36.245155,28.925770,69.121742,0.956213,16.207222,45.046654,29.773693,52.250351,137.785980,255.000000,255.000000,111.103096,529.962280,29.805639,30.621637,67.312416,31.017481,68.069366,3.128992,22.178471,4.992341,74.032547,101.164337,255.000000,255.000000,193.389114,35.549015,67.395782,572.091431,53.434189,67.354347,2.400206,9.505677,4.003738,49.043316,73.262779,48.821964,62.550640,9.177241,11.396896,197.433716,255.000000,244.996841,136.122864,33.778023,55.210960,10.269650,6.656691,26.448000,38.639622,1.451919,40.775261,69.269936,42.877098,130.657013,255.000000,255.000000,193.234695,60.750664,30.898640,2.951783,394.513794,74.926567,0.612359,10.758479,19.486452,33.746967,51.460499,73.798737,22.186161,53.321678,25.888899,132.819519,255.000000,255.000000,169.345657,34.533722,53.436516,61.582336,70.137108,62.536575,51.093590,53.569317,65.866295,61.497276,49.363590,104.328011,255.000000,255.000000,128.853455,28.675724,19.218422,-61.0,283.480225,33.064426,19.062588,69.905045,17.247831,43.244171,-149.0,353.940765,17.722736,64.683289,27.315826,41.670231,584.707031,137.802658,2550.000000,255.000000,137.915787,21.115459,17.862511,95.367287,24.832302,63.048553,34.646366,38.161854,55.418736,5.800240,32.055336,152.767258,255.000000,255.000000,150.485687,33.457859,54.153187,55.084053,39.078693,15.184362,71.425377,42.603699,66.147263,6.262023,15.945062,1.625657,54.935959,18.915865,82.893044,158.071625,255.000000,247.689148,116.773018,22.850695,31.614939,35.772598,73.555038,55.694126,70.093987,14.608850,30.700130,50.631134,74.812973,112.903076,255.000000,255.000000,145.006470,62.438286,50.911041,40.510765,40.415287,74.133568,68.364250,42.045067,304.643677,5.703604,40.300182,19.524031,9.010863,68.349098,62.334938,171.860794,255.000000,255.000000,157.092453,60.945274,43.030361,385.101959,56.852737,71.214790,48.503838,7.216677,30.418015,23.556034,65.195160,155.601624,255.000000,255.000000,200.808136,33.723774,63.947548,-123.0,614.773682,21.714075,61.103546,43.270863,30.291216,30.687210,57.413254,68.326752,71.502640,29.060925,8.775691,54.137791,139.917160,255.000000,255.000000,120.887383,13.285768,26.483786,21.762842,596.681274,46.828312,11.523950,17.266516,38.382462,57.279598,55.583420,138.138351,254.368500,2550.000000,128.890488,78.570244,63.474510,25.726372,14.393097,35.633347,43.912354,12.540868,18.164438,70.904182,64.524033,9.445167,50.844322,11.296674,38.329163,188.092422,255.000000,255.000000,132.500885,31.225887,17.422514,48.412598,36.196609,14.597270,37.644333,3.613254,39.966850,61.290775,39.761311,113.976234,255.000000,255.000000,184.147903,30.345074,38.394173,65.354370,13.679369,50.161839,3.272579,31.223976,40.069126,22.750767,66.947144,36.295910,30.591684,34.676891,28.626808,137.196045,255.000000,255.000000,161.610168,71.152458,62.157894,61.426785,4.689518,20.659021,19.985140,64.002281,49.843910,17.650421,6.675594,166.593353,255.000000,255.000000,139.649765,23.034758,5.583310,30.978649,28.693396,7.917845,9.239651,19.749716,6.639821,69.790611,14.275182,1.936887,71.066101,57.961578,202.427383,149.056747,255.000000,255.000000,168.732910,24.562620,6.220272,18.017096,7.593450,26.091194,2.397755,51.540680,71.141342,98.749451,6.004137,152.753067,255.000000,255.000000,200.811005,79.917747,43.929226,32.279411,67.963478,25.330544,-37.0,284.495758,6.936201,73.204765,19.805380,38.573750,34.798126,65.302132,28.986345,10.270257,199.906082,255.000000,243.312225,130.894394,41.723541,15.545962,41.448410,4.783601,39.400597,65.518616,74.474052,23.793522,48.081936,26.604507,174.797577,2550.000000,255.000000,151.849579,40.782646,36.503082,6.028434,51.623528,65.966385,32.745205,7.464529,56.986301,67.640785,51.515732,15.395627,67.234764,42.804417,81.946472,160.513718,255.000000,255.000000,-124.0,1232.517822,66.069511,10.988760,775.197937,13.464602,62.533089,2.293320,58.973572,23.623791,10.169403,17.558668,125.193954,255.000000,255.000000,191.727844,60.794720,18.242464,66.008530,19.572161,22.145775,-190.0,388.848785,64.101906,43.319378,15.446071,32.929527,49.887135,26.243525,36.303749,76.699089,189.598969,255.000000,255.000000,116.999893,72.769600,52.672337,14.344978,68.508514,24.071831,10.907624,-208.0,530.619751,30.336979,18.182842,30.261965,102.820816,255.000000,255.000000,157.355621,14.084815,37.324162,42.570915,2.151962,44.303535,29.658857,4.034749,69.080086,69.438927,40.014126,33.893734,28.616711,8.507636,27.073463,168.730194,2550.000000,255.000000,137.247498,-221.0,606.143494,53.527439,44.697151,22.577812,57.782909,76.689514,60.553822,74.476532,71.473114,19.048412,120.703117,255.000000,255.000000,-212.0,1429.345703,40.514259,0.216422,1.075037,5.597950,129.627151,48.704506,63.921890,325.549469,29.479826,54.988224,27.858105,-7.0,214.182205,30.584633,37.801872,161.535843,255.000000,255.000000,109.599586,58.600864,12.228879,21.607281,42.944855,57.042908,63.355465,31.052500,17.821033,69.281479,27.590584,162.422226,255.000000,255.000000,170.751205,32.163406,17.529039,59.998394,29.639252,27.514677,17.966473,1.738801,12.169317,10.781061,13.685239,67.164612,12.415943,68.860016,45.313778,192.238892,255.000000,255.000000,972.803284,67.543053,73.110817,20.185215,20.038177,565.602722,41.916500,63.062611,47.843979,67.892982,27.713106,83.752846,255.000000,255.000000,170.913315,31.358503,22.853081,21.426037,4.157455,14.726177,20.191753,32.618431,54.927040,49.100273,27.125896,27.069078,1.471659,25.013117,71.810211,167.607254,255.000000,255.000000,143.805206,126.555466,71.371063,122.335228,1286.270752,-103.0,1213.120483,70.026138,74.029655,93.847786,76.702614,84.312325,146.356369,255.000000,255.000000,176.900009,29.849022,43.408783,23.133173,71.621857,45.138054,12.812607,33.458546,63.575039,62.854759,10.525212,30.117283,27.689318,27.982668,68.054100,160.936859,255.000000,255.000000,255.000000,255.000000,255.000000,2550.000000,255.000000,255.000000,255.000000,255.000000,2550.000000,255.000000,255.000000,255.000000,255.000000,255.000000,196.006836,70.345009,12.041367,46.889435,45.087868,17.135658,27.691010,71.497482,38.424820,47.373577,53.786331,26.759636,58.221523,27.942076,27.555801,192.753418,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,2550.000000,255.000000,255.000000,173.130081,66.787491,67.509521,3.595160,58.817951,51.650040,13.076672,11.143249,37.090733,41.610474,12.842814,27.346222,2.532721,8.549923,28.727989,191.081757,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,252.885132,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,128.609467,18.533924,29.952227,58.192074,69.384697,64.737465,34.891174,53.630520,40.507294,365.383270,4.765791,52.388905,46.230846,70.884056,62.911232,-15.0,642.390564,41.054802,25.553520,53.830379,57.701126,29.902407,32.842117,49.650684,57.962318,47.446709,17.232460,12.621708,14.329309,37.136955,64.042381,52.600960,43.415424,60.040314,71.294220,5.008817,26.580570,47.612900,52.333241,10.655764,0.255490,2.0

In [11]:
tuple_size = data.shape[1]
num_datapoints = data.shape[0]

data.shape, num_datapoints, tuple_size

((5250, 1041), 5250, 1041)

#### Data Information
Pandas gives some simple review statistics/information about performance and the data itself

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Columns: 1041 entries, 0 to 1040
dtypes: float64(1041)
memory usage: 41.7 MB

#### Reading the data labels
Remember to change the filename to a directory on your device.

In [5]:
labels = pd.read_csv('C:\\Users\\User\\Documents\\CS Year 3\\ML\\Assignment 2\\trainlabels.txt', header=None)

In [6]:
labels.head()

    0
0  11
1   1
2  10
3   7
4  18

#### Separate Data Labels
A weird thing about the traindata.txt file is that in the last column, it has some labels: 0, 1, 2, 3. This suggests that the data is already labelled. I initially suspected that the data is generated from 4 clusters and each cluster defines 5 different classes which gives rise to the 20 different classes we have in the trainlabels.txt. However, this is a suspicion/theory. Try out your own and see how far you get. Have fun:)

In [14]:
data[tuple_size - 1].value_counts()

1040
2.0    1332
0.0    1328
1.0    1308
3.0    1282
Name: count, dtype: int64

In [15]:
data[tuple_size - 1].unique()

array([2., 1., 0., 3.])